method: CSSBli
src: en
tgt: es
data_params:
  data_dir: ./muse_data/
  output_dir: ./output/
  max_freq: 20000
  supervised:
    random: true
    max_count: -1
  mean_center: true
  unit_norm: true
model_params:
  save: True
  epochs: 5
  unsup_lr: 500
  unsup_epsilon: 1
  unsup_bsz: 8000
  unsup_steps: 100
  unsup_t: 0.1
  sup_steps: 2000
  sup_rcsls_k: 10
  sup_rcsls_tgt_rank: 100000
  sup_opt_params:
    name: SGD
    lr: 1.0
  sup_bsz: 400
  expand_dict_size: 10000 
  expand_rank: 20000 
